name: fake_fake_ip
description: A pure client-side app without ssr.
version: 0.0.1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  collection: ^1.18.0
  http: ^1.2.0
  jaspr: ^0.9.3

dev_dependencies:
  build_runner: ^2.4.0
  build_web_compilers: ^4.0.4
  lints: ^2.1.0

jaspr:
  uses-ssr: false
